// ─── CGRF Header ───────────────────────────────────────────────
// File:        apps/web/src/components/workspace/ComponentCatalog.jsx
// Stage:       07_BUILD
// SRS:         SRS-BUILDANDDO-COMMUNITY-001
// CAPS:        pending
// CK:          pending
// Seat:        BITS-CODEGEN
// Owner:       Citadel Nexus Inc.
// Created:     2026-09-10
// Depends:     apps/web/src/components/workspace/componentCatalogData.jsx,
//              apps/web/src/lib/observability/runtime.js
// EnumType:    Widget
// EnumEdges:   CONSUMES apps/web/src/components/workspace/componentCatalogData.jsx;
//              PRODUCES component_catalog.viewed; PRODUCES component_catalog.component_selected
// Intent:      Render the primitive inventory so a contributor stops writing a fourth button.
// ───────────────────────────────────────────────────────────────

import React, { useEffect, useMemo, useState } from 'react';
import { Boxes, GitPullRequest, Info, Search, ShieldAlert } from 'lucide-react';
import { reportAction } from '@/lib/observability/runtime';
import {
    CATALOG_CATEGORIES,
    CATALOG_ENTRIES,
    CATALOG_ENTRY_COUNT,
} from '@/components/workspace/componentCatalogData';
import { Badge, Card } from '@/components/site/ui';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';

const CONTRIBUTION_STEPS = [
    {
        title: 'Check it does not already exist',
        body: 'Search this catalogue first. Roughly two thirds of these modules are unused by application code, so the primitive you need is more likely missing an import than missing entirely.',
    },
    {
        title: 'Decide which layer it belongs to',
        body: 'components/ui holds unstyled-by-intent shadcn primitives — two-space indent, forwardRef, named exports, cn() for classes. components/site/ui holds the editorial broadsheet system that workspace pages actually use. components/workspace holds composed, product-specific pieces. Adding to the wrong layer is the most common review rejection here.',
    },
    {
        title: 'Match the house style of that directory exactly',
        body: 'The three layers disagree on formatting on purpose: components/ui uses two-space indent and double quotes because it is generated by the shadcn CLI, everything else uses four-space indent and single quotes. Follow the neighbouring file, not your editor default.',
    },
    {
        title: 'Register it here',
        body: 'A new module in components/ui needs an entry in componentCatalogData.jsx with its module path, exports, key props, and either a standalone preview or a note saying which provider it needs. An entry that fakes a preview is worse than no preview.',
    },
    {
        title: 'Prove it renders',
        body: 'Run npm run lint --prefix apps/web and npm run build, then open the catalogue and look at your preview. A component that only compiles is not a component that works.',
    },
];

/**
 * Live component catalogue and contributor guide.
 *
 * Previews mount per category rather than all at once — a single page holding
 * every primitive in the directory at the same time is both slow and unusable.
 *
 * @returns {JSX.Element} The catalogue.
 */
export default function ComponentCatalog() {
    const [categoryId, setCategoryId] = useState(CATALOG_CATEGORIES[0].id);
    const [query, setQuery] = useState('');
    const [openEntryId, setOpenEntryId] = useState(null);

    useEffect(() => {
        reportAction('component_catalog.viewed', {
            entry_count: CATALOG_ENTRY_COUNT,
            category_count: CATALOG_CATEGORIES.length,
        });
    }, []);

    const term = query.trim().toLowerCase();

    const visible = useMemo(() => {
        if (term) {
            return CATALOG_ENTRIES.filter(
                (entry) =>
                    entry.name.toLowerCase().includes(term) ||
                    entry.module.toLowerCase().includes(term) ||
                    entry.exports.some((name) => name.toLowerCase().includes(term)),
            );
        }
        return CATALOG_ENTRIES.filter((entry) => entry.category === categoryId);
    }, [term, categoryId]);

    const category = CATALOG_CATEGORIES.find((c) => c.id === categoryId);

    const select = (entry) => {
        const next = openEntryId === entry.id ? null : entry.id;
        setOpenEntryId(next);
        if (next) {
            reportAction('component_catalog.component_selected', {
                component: entry.name,
                module: entry.module,
                category: entry.category,
                has_preview: Boolean(entry.preview),
            });
        }
    };

    return (
        <div className="space-y-6">
            <Card className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between">
                <div className="flex items-start gap-3">
                    <span className="flex h-10 w-10 shrink-0 items-center justify-center border border-border bg-secondary text-primary">
                        <Boxes className="h-5 w-5" />
                    </span>
                    <div className="text-sm">
                        <p className="font-medium">
                            {CATALOG_ENTRY_COUNT} primitive modules in components/ui
                        </p>
                        <p className="mt-0.5 text-muted-foreground">
                            Every module in the directory has an entry. Modules needing a
                            provider say so instead of showing an empty preview.
                        </p>
                    </div>
                </div>
                <div className="grid w-full gap-2 sm:w-64">
                    <Label htmlFor="catalog-search" className="sr-only">
                        Search components
                    </Label>
                    <div className="relative">
                        <Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
                        <Input
                            id="catalog-search"
                            value={query}
                            onChange={(e) => setQuery(e.target.value)}
                            placeholder="Search name or export"
                            className="pl-9"
                        />
                    </div>
                </div>
            </Card>

            {!term && (
                <div className="flex flex-wrap gap-2">
                    {CATALOG_CATEGORIES.map((c) => {
                        const count = CATALOG_ENTRIES.filter((e) => e.category === c.id).length;
                        const isActive = c.id === categoryId;
                        return (
                            <button
                                key={c.id}
                                type="button"
                                onClick={() => {
                                    setCategoryId(c.id);
                                    setOpenEntryId(null);
                                }}
                                className={
                                    isActive
                                        ? 'border border-primary/40 bg-primary/10 px-3 py-1.5 text-xs font-semibold uppercase tracking-wider text-primary'
                                        : 'border border-border bg-secondary/40 px-3 py-1.5 text-xs font-semibold uppercase tracking-wider text-muted-foreground transition-colors hover:text-foreground'
                                }
                            >
                                {c.label} ({count})
                            </button>
                        );
                    })}
                </div>
            )}

            {!term && category && (
                <p className="text-sm text-muted-foreground">{category.description}</p>
            )}

            {term && (
                <p className="text-sm text-muted-foreground">
                    {visible.length} module{visible.length === 1 ? '' : 's'} matching
                    &ldquo;{query.trim()}&rdquo;
                </p>
            )}

            {visible.length === 0 ? (
                <Card className="p-8 text-center text-sm text-muted-foreground">
                    Nothing in the catalogue matches that. Try an export name such as
                    DialogContent.
                </Card>
            ) : (
                <ul className="space-y-4">
                    {visible.map((entry) => {
                        const isOpen = openEntryId === entry.id;
                        const Preview = entry.preview;
                        return (
                            <li key={entry.id}>
                                <Card className="p-5">
                                    <button
                                        type="button"
                                        onClick={() => select(entry)}
                                        aria-expanded={isOpen}
                                        className="flex w-full flex-col items-start gap-1 text-left"
                                    >
                                        <div className="flex flex-wrap items-center gap-2">
                                            <span className="font-display text-base font-semibold tracking-tight">
                                                {entry.name}
                                            </span>
                                            <Badge tone={entry.preview ? 'teal' : 'amber'}>
                                                {entry.preview ? 'live preview' : 'needs provider'}
                                            </Badge>
                                            <span className="text-xs text-muted-foreground">
                                                {entry.exports.length} export
                                                {entry.exports.length === 1 ? '' : 's'}
                                            </span>
                                        </div>
                                        <code className="font-evidence text-[11px] text-muted-foreground">
                                            import &#123; {entry.exports[0]} &#125; from &apos;
                                            {entry.module}&apos;
                                        </code>
                                    </button>

                                    <p className="mt-2 text-sm leading-relaxed text-muted-foreground">
                                        {entry.summary}
                                    </p>

                                    <div className="mt-4 border-t border-border/60 pt-4">
                                        <p className="mb-3 text-[11px] font-semibold uppercase tracking-wider text-muted-foreground">
                                            Preview
                                        </p>
                                        {Preview ? (
                                            <div className="border border-dashed border-border p-4">
                                                <Preview />
                                            </div>
                                        ) : (
                                            <p className="flex items-start gap-2 border border-dashed border-[hsl(var(--amber))]/40 bg-[hsl(var(--amber))]/5 p-4 text-xs leading-relaxed text-muted-foreground">
                                                <ShieldAlert className="mt-0.5 h-4 w-4 shrink-0 text-amber-warm" />
                                                {entry.previewNote}
                                            </p>
                                        )}
                                    </div>

                                    {isOpen && (
                                        <div className="mt-4 grid gap-4 border-t border-border/60 pt-4 sm:grid-cols-2">
                                            <div>
                                                <p className="mb-2 text-[11px] font-semibold uppercase tracking-wider text-muted-foreground">
                                                    Key props
                                                </p>
                                                <dl className="space-y-1.5 text-xs">
                                                    {entry.props.map((prop) => (
                                                        <div key={prop.name}>
                                                            <dt className="font-evidence text-foreground">
                                                                {prop.name}
                                                            </dt>
                                                            <dd className="text-muted-foreground">
                                                                {prop.type}
                                                            </dd>
                                                        </div>
                                                    ))}
                                                </dl>
                                            </div>
                                            <div>
                                                <p className="mb-2 text-[11px] font-semibold uppercase tracking-wider text-muted-foreground">
                                                    Exports
                                                </p>
                                                <p className="font-evidence text-xs leading-relaxed text-muted-foreground">
                                                    {entry.exports.join(', ')}
                                                </p>
                                            </div>
                                        </div>
                                    )}
                                </Card>
                            </li>
                        );
                    })}
                </ul>
            )}

            <section className="space-y-3">
                <h2 className="font-display text-lg font-semibold tracking-tight">
                    How to contribute a component
                </h2>
                <ol className="space-y-3">
                    {CONTRIBUTION_STEPS.map((step, index) => (
                        <li key={step.title}>
                            <Card className="p-4">
                                <div className="flex gap-3">
                                    <span className="font-evidence mt-0.5 text-[11px] text-muted-foreground">
                                        {String(index + 1).padStart(2, '0')}
                                    </span>
                                    <div className="min-w-0">
                                        <p className="text-sm font-medium">{step.title}</p>
                                        <p className="mt-1 text-sm leading-relaxed text-muted-foreground">
                                            {step.body}
                                        </p>
                                    </div>
                                </div>
                            </Card>
                        </li>
                    ))}
                </ol>
                <Card className="p-4">
                    <div className="flex items-start gap-3">
                        <GitPullRequest className="mt-0.5 h-4 w-4 shrink-0 text-primary" />
                        <p className="text-sm leading-relaxed text-muted-foreground">
                            Open a{' '}
                            <span className="font-medium text-foreground">
                                Good first issue
                            </span>{' '}
                            or{' '}
                            <span className="font-medium text-foreground">
                                Workspace page enhancement
                            </span>{' '}
                            form before writing the component, so the acceptance criteria
                            exist before the diff does. One pull request per SRS code.
                        </p>
                    </div>
                </Card>
            </section>

            <p className="flex items-start gap-2 text-xs leading-relaxed text-muted-foreground/70">
                <Info className="mt-0.5 h-3.5 w-3.5 shrink-0" />
                This catalogue is hand-maintained, because a live preview cannot be
                generated from a directory listing. If you add a module to components/ui
                and skip its entry here, the count above stops matching the directory —
                that mismatch is the intended alarm.
            </p>
        </div>
    );
}

export { ComponentCatalog };
