# ─── CGRF Header ─────────────────────────────
# File:        libs/semantic_twin/__init__.py
# Stage:       07_BUILD
# SRS:         SRS-BUILDANDDO-SEMANTIC-TWIN-001
# CAPS:        pending
# CK:          pending
# Dispatch:    VCC-BUILDANDDO-SEMANTIC-TWIN-001
# Seat:        BITS-CODEGEN
# Owner:       Citadel Nexus Inc.
# Created:     2026-09-19
# Depends:     libs/semantic_twin/contracts.py, libs/semantic_twin/identity.py, libs/semantic_twin/merkle.py, libs/semantic_twin/receipts.py, libs/semantic_twin/relations.py, libs/semantic_twin/models.py, libs/semantic_twin/transactions.py, libs/semantic_twin/promotions.py, libs/semantic_twin/transitions.py, libs/semantic_twin/vocabulary.py
# EnumType:    Scaffold
# EnumEdges:   CONSUMES libs/semantic_twin/contracts.py; CONSUMES libs/semantic_twin/identity.py; CONSUMES libs/semantic_twin/merkle.py; CONSUMES libs/semantic_twin/receipts.py; CONSUMES libs/semantic_twin/relations.py; CONSUMES libs/semantic_twin/models.py; CONSUMES libs/semantic_twin/transactions.py; CONSUMES libs/semantic_twin/promotions.py; CONSUMES libs/semantic_twin/transitions.py; CONSUMES libs/semantic_twin/vocabulary.py
# DAG Node:    semantic-twin.phase-0.api
# Intent:      Expose the frozen Phase 0 vocabulary, transition policies and envelopes through one stable import surface.
# ───────────────────────────────────────────────────────────


"""Expose the Living Semantic System Twin version-two contract surface."""

from .contracts import (
    SCHEMA_VERSION,
    CitadelError,
    ContractError,
)
from .identity import (
    ENTITY_NAMESPACES,
    EntityType,
    NAMESPACE_REGISTRY,
    SemanticId,
    SubjectRef,
    ValidTime,
)
from .merkle import (
    InclusionVerificationReceipt,
    HashAlgorithm,
    ContentDigest,
    PayloadDigest,
    ArtifactDigest,
    DeploymentDigest,
    ContextRoot,
    SemanticRoot,
    EvidenceRoot,
    SourceRoot,
    ParentRoot,
    SourceRevision,
    CanonicalSerialization,
    EpochScope,
    EpochBoundary,
    MerkleLeaf,
    MerkleNode,
    MerkleRoot,
    MerkleEpoch,
    Attestation,
    ProofSide,
    ProofStep,
    InclusionProof,
    MerkleBinding,
)
from .receipts import (
    EvidenceKind,
    EvidenceReference,
    ActorType,
    AuthorityGrant,
    PolicyDecisionReceipt,
    IssueSeverity,
    ShaclIssue,
    ShaclValidationResult,
    VerificationMethod,
    PostconditionResult,
    TevvResult,
    VerificationReceipt,
    CausalSupport,
    ExecutionOutcome,
    ExecutionReceipt,
    CorpusValidation,
)
from .relations import (
    RelationContract,
    RELATION_CONTRACTS,
    Relation,
)
from .models import (
    AxisState,
    Source,
    ObjectState,
    Provenance,
    Ownership,
    Authority,
    Runtime,
    Documentation,
    CanonicalObjectEnvelope,
    EventSubject,
    EventContext,
    EventEvidence,
    CanonicalEventEnvelope,
)
from .transactions import (
    Actor,
    TransactionIntent,
    StateRoots,
    ChangeProposal,
    CompensationPlan,
    ChangeContract,
    RollbackReceipt,
    GraphPromotionReceipt,
    SemanticTransaction,
)
from .promotions import (
    PromotionProof,
)
from .transitions import (
    CAUSAL_TRANSITIONS,
    CGRF_ACTION_TRANSITIONS,
    CORPUS_USE_TRANSITIONS,
    EVIDENCE_TRANSITIONS,
    FORBIDDEN_AUTOMATIC_PROMOTIONS,
    MERKLE_TRANSITIONS,
    SEMANTIC_TRANSACTION_TRANSITIONS,
    SHACL_TRANSITIONS,
    TEVV_TRANSITIONS,
    InvalidTransitionError,
    StateDelta,
    apply_state_deltas,
    allowed_transitions,
    can_automatically_promote,
    can_transition,
    require_transition,
)
from .vocabulary import (
    AUTHORITY_TIER_FRICTION,
    AUTHORITY_TIER_NAMES,
    DESIGN_LAWS,
    RELATION_PREDICATE_GROUPS,
    AuthorityTier,
    CausalState,
    CgrfActionState,
    CorpusUseState,
    EvidenceState,
    MerkleState,
    RelationPredicate,
    SemanticTransactionState,
    ShaclState,
    StateAxis,
    TevvState,
)

__all__ = [
    "ENTITY_NAMESPACES",
    "InclusionVerificationReceipt",
    "AUTHORITY_TIER_FRICTION",
    "AUTHORITY_TIER_NAMES",
    "Actor",
    "ActorType",
    "ArtifactDigest",
    "Attestation",
    "Authority",
    "AuthorityGrant",
    "AuthorityTier",
    "AxisState",
    "CAUSAL_TRANSITIONS",
    "CGRF_ACTION_TRANSITIONS",
    "CORPUS_USE_TRANSITIONS",
    "CanonicalEventEnvelope",
    "CanonicalObjectEnvelope",
    "CanonicalSerialization",
    "CausalState",
    "CausalSupport",
    "CgrfActionState",
    "ChangeContract",
    "ChangeProposal",
    "CitadelError",
    "CompensationPlan",
    "ContentDigest",
    "ContextRoot",
    "ContractError",
    "CorpusUseState",
    "CorpusValidation",
    "DESIGN_LAWS",
    "DeploymentDigest",
    "Documentation",
    "EVIDENCE_TRANSITIONS",
    "EntityType",
    "EpochBoundary",
    "EpochScope",
    "EventContext",
    "EventEvidence",
    "EventSubject",
    "EvidenceKind",
    "EvidenceReference",
    "EvidenceRoot",
    "EvidenceState",
    "ExecutionOutcome",
    "ExecutionReceipt",
    "FORBIDDEN_AUTOMATIC_PROMOTIONS",
    "GraphPromotionReceipt",
    "HashAlgorithm",
    "InclusionProof",
    "InvalidTransitionError",
    "IssueSeverity",
    "MERKLE_TRANSITIONS",
    "MerkleBinding",
    "MerkleEpoch",
    "MerkleLeaf",
    "MerkleNode",
    "MerkleRoot",
    "MerkleState",
    "NAMESPACE_REGISTRY",
    "ObjectState",
    "Ownership",
    "ParentRoot",
    "PayloadDigest",
    "PolicyDecisionReceipt",
    "PostconditionResult",
    "PromotionProof",
    "ProofSide",
    "ProofStep",
    "Provenance",
    "RELATION_CONTRACTS",
    "RELATION_PREDICATE_GROUPS",
    "Relation",
    "RelationContract",
    "RelationPredicate",
    "RollbackReceipt",
    "Runtime",
    "SCHEMA_VERSION",
    "SEMANTIC_TRANSACTION_TRANSITIONS",
    "SHACL_TRANSITIONS",
    "SemanticId",
    "SemanticRoot",
    "SemanticTransaction",
    "SemanticTransactionState",
    "ShaclIssue",
    "ShaclState",
    "ShaclValidationResult",
    "Source",
    "SourceRevision",
    "SourceRoot",
    "StateAxis",
    "StateDelta",
    "StateRoots",
    "SubjectRef",
    "TEVV_TRANSITIONS",
    "TevvResult",
    "TevvState",
    "TransactionIntent",
    "ValidTime",
    "VerificationMethod",
    "VerificationReceipt",
    "allowed_transitions",
    "apply_state_deltas",
    "can_automatically_promote",
    "can_transition",
    "require_transition",
]
