# ─── CGRF Header ───────────────────────────────────────────────
# File:        libs/career_passport/passport.py
# Stage:       07_BUILD
# SRS:         SRS-BUILDANDDO-UPGRADE-001
# CAPS:        pending
# CK:          pending
# Dispatch:    VCC-BUILDANDDO-UPGRADE-001
# Seat:        BITS-CODEGEN
# Owner:       Citadel Nexus Inc.
# Created:     2026-09-22
# Depends:     libs/career_passport/models.py, libs/capability_tokens/verification.py, libs/evolution/common.py
# EnumType:    Service
# EnumEdges:   CONSUMES libs/career_passport/models.py; CONSUMES libs/capability_tokens/verification.py; CONSUMES libs/evolution/common.py
# Intent:      Derive claim standing from exact work and receiving-pinned independent review instead of imported verified flags.
# ───────────────────────────────────────────────────────────────

"""Project personal claims without changing competence, trust or authority."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime

from libs.capability_tokens.verification import ReviewPolicy, require_review
from libs.evolution.common import digest
from libs.semantic_twin.contracts import ContractError, require
from libs.semantic_twin.identity import SemanticId
from libs.semantic_twin.merkle import ContentDigest
from libs.semantic_twin.vocabulary import AuthorityTier

from .models import Contribution, Participation, WorkBundle

CHECKS = (
    "career.identity",
    "career.participation",
    "career.capability",
    "career.scope",
)


@dataclass(frozen=True, slots=True)
class ClaimView:
    """Hold a derived view; deserialize source bundles, never this trust result."""

    contribution: Contribution
    state: str
    reasons: tuple[str, ...]
    review_sha256: str | None = None

    def to_dict(self) -> dict[str, object]:
        """Expose provenance and participation alongside the derived standing."""
        return {
            "id": str(self.contribution.subject.semantic_id),
            "statement": self.contribution.statement,
            "contribution": self.contribution.to_dict(),
            "state": self.state,
            "evidence_state": "VERIFIED" if self.state == "VERIFIED" else "OBSERVED",
            "reasons": list(self.reasons),
            "review_sha256": self.review_sha256,
        }


@dataclass(frozen=True, slots=True)
class Passport:
    """Represent an advisory projection generated by project_passport."""

    person: SemanticId
    workspace: str
    as_of: datetime
    work_sha256: str
    claims: tuple[ClaimView, ...]
    gaps: tuple[str, ...]

    @property
    def verified(self) -> tuple[ClaimView, ...]:
        """Select exact, independently reviewed personal contributions only."""
        return tuple(c for c in self.claims if c.state == "VERIFIED")

    def to_dict(self) -> dict[str, object]:
        """Serialize counts without inventing a competence percentage or duration."""
        return {
            "schema_version": "buildanddo.career-passport/v1",
            "person": str(self.person),
            "workspace": self.workspace,
            "as_of": self.as_of.isoformat(),
            "work_sha256": self.work_sha256,
            "claims": [c.to_dict() for c in self.claims],
            "gaps": list(self.gaps),
            "verified_personal_claims": len(self.verified),
            "employment_years": None,
            "authority_granted": False,
        }


def project_passport(
    work: WorkBundle,
    person: SemanticId,
    *,
    workspace: str,
    at: datetime,
    policy: ReviewPolicy | None = None,
) -> Passport:
    """Recompute standing using an independently supplied receiving review policy.

    Args:
        work: Untrusted observations and candidate review receipts.
        person: Identity selected by the authenticated receiving process.
        workspace: Expected scope supplied separately from imported data.
        at: Current aware time; recapture cannot renew a review.
        policy: Externally authenticated verifier and receipt pins. Never take
            these from the work bundle, a job posting or a generated passport.
    """
    person.require_namespace("person")
    require(at.tzinfo is not None and at >= work.captured_at, "future work capture")
    require(work.workspace == workspace, "career workspace mismatch")
    artifacts = {a.source: a for a in work.artifacts}
    claims: list[ClaimView] = []
    for contribution in sorted(
        work.contributions, key=lambda c: str(c.subject.semantic_id)
    ):
        state, reasons, pin = "UNREVIEWED", [], None
        if (
            contribution.participant != person
            or contribution.participation is Participation.AGENT_EXECUTED
        ):
            state, reasons = (
                "NOT_PERSONAL",
                [
                    "Work is attributed to another participant; it cannot become this person's experience."
                ],
            )
        elif any(source not in artifacts for source in contribution.artifact_ids):
            state, reasons = (
                "MISSING_EVIDENCE",
                ["An exact work artifact is unavailable."],
            )
        elif policy is None:
            reasons = [
                "Independent participation/capability review has not been authenticated."
            ]
        else:
            selected = [
                a
                for source, a in artifacts.items()
                if source in contribution.artifact_ids
            ]
            matching = [
                r for r in work.reviews if r.result.subject == contribution.subject
            ]
            # Conflicting current pinned decisions cannot be hidden by selecting a PASS.
            pinned = [
                r
                for r in matching
                if ContentDigest(digest(r)) in policy.receipt_digests
            ]
            if not pinned:
                reasons = ["No receiving-pinned review covers this exact contribution."]
            else:
                newest = max(r.result.evaluated_at for r in pinned)
                current = [r for r in pinned if r.result.evaluated_at == newest]
                if len(current) != 1:
                    state, reasons = (
                        "CONFLICTING",
                        ["Competing pinned reviews have the same decision time."],
                    )
                else:
                    receipt = current[0]
                    try:
                        require(
                            contribution.agent_assistance is not None,
                            "agent assistance has not been reviewed",
                        )
                        require(
                            receipt.result.actor_id == contribution.producer,
                            "review producer mismatch",
                        )
                        require(
                            receipt.result.verifier_id != person,
                            "personal self-review is not independent",
                        )
                        require(
                            all(
                                a.producer != receipt.result.verifier_id
                                for a in selected
                            ),
                            "reviewer produced the work evidence",
                        )
                        require_review(
                            receipt,
                            contribution.subject,
                            policy,
                            at=at,
                            tier=AuthorityTier.A0,
                            checks=CHECKS,
                            sources=contribution.artifact_ids,
                            since=max(
                                [
                                    contribution.occurred_at,
                                    *(a.recorded_at for a in selected),
                                ]
                            ),
                        )
                        state, pin = "VERIFIED", digest(receipt)
                    except ContractError as error:
                        state = "STALE" if "stale" in str(error) else "REVIEW_REJECTED"
                        reasons = [str(error)]
        claims.append(ClaimView(contribution, state, tuple(reasons), pin))
    gaps = list(work.gaps)
    if not any(c.state == "VERIFIED" for c in claims):
        gaps.append(
            "No independently verified personal career claim is available for application prose."
        )
    gaps.append(
        "Employment duration, legal eligibility and personal attestations are not inferred from development history."
    )
    return Passport(
        person, workspace, at, digest(work), tuple(claims), tuple(dict.fromkeys(gaps))
    )
