#!/usr/bin/env python3
# ─── CGRF Header ───────────────────────────────────────────────
# File:        scripts/ci/changelog_gen.py
# Stage:       11_COMMIT
# SRS:         SRS-BUILDANDDO-CHANGELOG-001
# CAPS:        pending
# CK:          pending
# Seat:        BITS-CODEGEN
# Owner:       Citadel Nexus Inc.
# Created:     2026-09-10
# Depends:     CHANGELOG.md, scripts/ci/telemetry_snapshot.py
# EnumType:    Service
# EnumEdges:   CONSUMES git history; PRODUCES CHANGELOG.md;
#              PRODUCES state/changelog/latest.json;
#              GATES .github/workflows/pr-governance.yml
# Intent:      Derive the changelog from the commits that actually landed, and
#              emit the same facts as machine-readable release telemetry.
# ───────────────────────────────────────────────────────────────
"""Generate CHANGELOG.md from git history and summarise it as JSON.

The changelog body between the generated markers is a pure function of the
commit range, so running this twice produces the same bytes and `--check` can
tell CI whether the committed file still matches the history it claims to
describe. Anything written outside the markers - the header, the preamble, a
hand-written release note - is preserved untouched.

Commits are grouped by the date they landed on the target ref and classified by
their conventional-commit type. Merge commits are skipped: they record when a
branch arrived, not what it did.

Standard library only, matching the other scripts in this directory.
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import re
import subprocess
import sys
from pathlib import Path

BEGIN = "<!-- changelog:generated:begin -->"
END = "<!-- changelog:generated:end -->"

# Separators must not be whitespace. The obvious ASCII unit/record separators
# (\x1f, \x1e) are whitespace to str.strip(), which silently ate the trailing
# record - and with it the oldest commit - when git output was stripped.
FIELD = "\x01"
RECORD = "\x02"

# Conventional-commit type -> Keep a Changelog section. Types absent from this
# map land in "Other" rather than being dropped, so an unrecognised prefix is
# visible in the output instead of silently disappearing.
TYPE_SECTIONS = {
    "feat": "Added",
    "test": "Added",
    "fix": "Fixed",
    "security": "Security",
    "refactor": "Changed",
    "docs": "Changed",
    "chore": "Changed",
    "ci": "Changed",
    "build": "Changed",
    "perf": "Changed",
    "style": "Changed",
    "content": "Changed",
    "revert": "Removed",
    "remove": "Removed",
}

SECTION_ORDER = ["Added", "Changed", "Deprecated", "Removed", "Fixed", "Security", "Other"]

SUBJECT_RE = re.compile(r"^(?P<type>[a-z]+)(?:\((?P<scope>[^)]*)\))?(?P<breaking>!)?:\s*(?P<desc>.+)$")
SRS_RE = re.compile(r"\bSRS-[A-Z0-9]+(?:-[A-Z0-9]+)+\b")

PREAMBLE = """All notable changes to this repository, derived from the commits that actually
landed on `main`. Generated by `scripts/ci/changelog_gen.py`; edit the script or
the commit messages, not the block below.

The format follows [Keep a Changelog](https://keepachangelog.com/en/1.1.0/).
There are no tagged releases yet, so entries are grouped by the date they landed
rather than by version. An entry records that a change shipped - not that its
behaviour was verified; verification evidence lives with the SRS spec named in
the entry.
"""


class ChangelogError(RuntimeError):
    """A changelog generation step could not complete."""


def git(root: Path, *args: str) -> str:
    """Run a git command in `root` and return its stdout.

    Args:
        root: Repository root.
        *args: Arguments passed to git.

    Returns:
        Captured stdout with surrounding whitespace stripped.

    Raises:
        ChangelogError: When git exits non-zero.
    """
    proc = subprocess.run(["git", "-C", str(root), *args], text=True, capture_output=True)
    if proc.returncode != 0:
        raise ChangelogError(proc.stderr.strip() or f"git {' '.join(args)} failed")
    return proc.stdout.strip()


def last_tag(root: Path, ref: str) -> str:
    """Return the most recent tag reachable from `ref`, or an empty string."""
    try:
        return git(root, "describe", "--tags", "--abbrev=0", ref)
    except ChangelogError:
        return ""


def read_commits(root: Path, ref: str, since_ref: str, since_date: str) -> list[dict]:
    """Read non-merge commits on `ref`, newest first.

    Args:
        root: Repository root.
        ref: Ref to read history from.
        since_ref: Exclusive lower bound ref, such as the last tag. May be empty.
        since_date: Lower bound date (`YYYY-MM-DD`). May be empty.

    Returns:
        One dict per commit with sha, date, subject, body and srs codes.
    """
    fmt = FIELD.join(["%h", "%H", "%cs", "%s", "%b"]) + RECORD
    args = ["log", "--no-merges", f"--pretty=format:{fmt}"]
    if since_date:
        args.append(f"--since={since_date}")
    args.append(f"{since_ref}..{ref}" if since_ref else ref)

    raw = git(root, *args)
    commits: list[dict] = []
    for chunk in raw.split(RECORD):
        chunk = chunk.strip("\n")
        if not chunk.strip():
            continue
        parts = chunk.split(FIELD)
        if len(parts) < 5:
            continue
        short, full, date, subject, body = parts[0], parts[1], parts[2], parts[3], parts[4]
        commits.append(
            {
                "sha": short,
                "full_sha": full,
                "date": date,
                "subject": subject.strip(),
                "srs": sorted(set(SRS_RE.findall(f"{subject}\n{body}"))),
            }
        )
    return commits


def classify(subject: str) -> tuple[str, str, str]:
    """Split a commit subject into its changelog section, scope and description.

    Args:
        subject: Commit subject line.

    Returns:
        A `(section, scope, description)` triple. `scope` is empty when the
        subject carries none, and `section` is "Other" for a subject that is not
        a conventional commit.
    """
    match = SUBJECT_RE.match(subject)
    if not match:
        return "Other", "", subject
    kind = match.group("type")
    section = TYPE_SECTIONS.get(kind, "Other")
    return section, (match.group("scope") or "").strip(), match.group("desc").strip()


def entry_line(commit: dict, scope: str, description: str) -> str:
    """Render one changelog bullet."""
    text = f"{scope}: {description}" if scope else description
    refs = [f"`{commit['sha']}`"]
    refs.extend(commit["srs"])
    return f"- {text} ({', '.join(refs)})"


def build_sections(commits: list[dict]) -> list[dict]:
    """Group commits by landing date, then by changelog section.

    Args:
        commits: Commits newest first.

    Returns:
        A list of `{date, sections: {name: [lines]}}` newest first.
    """
    by_date: dict[str, dict[str, list[str]]] = {}
    for commit in commits:
        section, scope, description = classify(commit["subject"])
        day = by_date.setdefault(commit["date"], {})
        day.setdefault(section, []).append(entry_line(commit, scope, description))
    return [
        {"date": date, "sections": by_date[date]}
        for date in sorted(by_date, reverse=True)
    ]


def render_block(days: list[dict]) -> str:
    """Render the managed changelog block, markers included."""
    lines = [BEGIN, ""]
    if not days:
        lines.append("No commits in the selected range.")
        lines.append("")
    for day in days:
        lines.append(f"## {day['date']}")
        lines.append("")
        for name in SECTION_ORDER:
            entries = day["sections"].get(name)
            if not entries:
                continue
            lines.append(f"### {name}")
            lines.append("")
            lines.extend(entries)
            lines.append("")
    lines.append(END)
    return "\n".join(lines)


def render_document(existing: str, block: str, title: str) -> str:
    """Insert `block` into `existing`, or build the file when it has no markers.

    Args:
        existing: Current file contents, empty when the file is absent.
        block: Rendered managed block including its markers.
        title: Document H1.

    Returns:
        The full file contents.
    """
    if BEGIN in existing and END in existing:
        head, _, rest = existing.partition(BEGIN)
        _, _, tail = rest.partition(END)
        return f"{head}{block}{tail}"

    header = (
        "<!-- ─── CGRF Header ───────────────────────────────────────────────\n"
        "File:        CHANGELOG.md\n"
        "Stage:       11_COMMIT\n"
        "SRS:         SRS-BUILDANDDO-CHANGELOG-001\n"
        "CAPS:        pending\n"
        "CK:          pending\n"
        "Seat:        BITS-CODEGEN\n"
        "Owner:       Citadel Nexus Inc.\n"
        "Created:     2026-09-10\n"
        "Depends:     scripts/ci/changelog_gen.py\n"
        "EnumType:    Doc\n"
        "EnumEdges:   CONSUMES git history; VALIDATES scripts/ci/changelog_gen.py\n"
        "Intent:      Record what actually landed on main, generated from the commits themselves.\n"
        "─────────────────────────────────────────────────────────────── -->\n"
    )
    return f"{header}\n# {title}\n\n{PREAMBLE}\n{block}\n"


def build_summary(commits: list[dict], days: list[dict], ref: str, since_ref: str, since_date: str) -> dict:
    """Build the machine-readable summary of this generation run."""
    categories: dict[str, int] = {}
    for day in days:
        for name, entries in day["sections"].items():
            categories[name] = categories.get(name, 0) + len(entries)
    srs_codes = sorted({code for commit in commits for code in commit["srs"]})
    dates = [day["date"] for day in days]
    return {
        "schema_version": 1,
        "generated_at": dt.datetime.now(dt.timezone.utc).isoformat(),
        "source": {
            "ref": ref,
            "since_ref": since_ref,
            "since_date": since_date,
            "merge_commits": "excluded",
        },
        "entry_count": len(commits),
        "date_range": {
            "first": dates[-1] if dates else "",
            "last": dates[0] if dates else "",
            "days_with_changes": len(dates),
        },
        "srs_codes": srs_codes,
        "srs_code_count": len(srs_codes),
        "commits_without_srs": sum(1 for commit in commits if not commit["srs"]),
        "categories": dict(sorted(categories.items())),
        "unclassified_count": categories.get("Other", 0),
    }


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--root", default=".")
    ap.add_argument("--ref", default="", help="ref to read history from (default: main, else HEAD)")
    ap.add_argument("--since-tag", default="", help="exclusive lower-bound tag (default: the last tag, if any)")
    ap.add_argument("--all", action="store_true", help="ignore tags and read the full history")
    ap.add_argument("--since-date", default="", help="lower-bound date, YYYY-MM-DD")
    ap.add_argument("--title", default="Changelog")
    ap.add_argument("--output", default="CHANGELOG.md")
    ap.add_argument("--summary", default="state/changelog/latest.json")
    ap.add_argument("--no-summary", action="store_true", help="skip the JSON summary")
    ap.add_argument("--check", action="store_true", help="fail when the committed changelog is stale")
    args = ap.parse_args()

    root = Path(args.root).resolve()

    # A CI checkout of a pull request has no local `main`, and comparing against
    # HEAD there would demand entries for commits whose landing sha and date do
    # not exist yet. `origin/main` is the branch this changelog describes.
    ref = args.ref
    if not ref:
        for candidate in ("main", "origin/main", "HEAD"):
            try:
                git(root, "rev-parse", "--verify", candidate)
                ref = candidate
                break
            except ChangelogError:
                continue
    if not ref:
        print("changelog: no readable ref (tried main, origin/main, HEAD)", file=sys.stderr)
        return 2

    since_ref = "" if args.all else (args.since_tag or last_tag(root, ref))

    try:
        commits = read_commits(root, ref, since_ref, args.since_date)
    except ChangelogError as err:
        print(f"changelog: {err}", file=sys.stderr)
        return 2

    days = build_sections(commits)
    block = render_block(days)

    out = root / args.output
    existing = out.read_text(encoding="utf-8") if out.is_file() else ""
    document = render_document(existing, block, args.title)

    summary = build_summary(commits, days, ref, since_ref, args.since_date)

    if not args.no_summary:
        summary_path = root / args.summary
        summary_path.parent.mkdir(parents=True, exist_ok=True)
        summary_path.write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    if args.check:
        if not existing:
            print(f"changelog: {args.output} is missing; run scripts/ci/changelog_gen.py", file=sys.stderr)
            return 1
        if existing != document:
            print(
                f"changelog: {args.output} does not match the history on {ref}; "
                "run `python scripts/ci/changelog_gen.py` and commit the result",
                file=sys.stderr,
            )
            return 1
        print(f"changelog: {args.output} is current ({summary['entry_count']} entries)", file=sys.stderr)
        return 0

    out.write_text(document, encoding="utf-8")
    print(
        f"changelog: {summary['entry_count']} entries across {summary['date_range']['days_with_changes']} "
        f"day(s) -> {args.output}",
        file=sys.stderr,
    )
    print(json.dumps(summary, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
